apiVersion: v1
kind: Pod
metadata:
 name: azure-files-pod
spec:
 containers:
  - image: openhack/minecraft-server
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /data
 volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      shareName: aksshare
      readOnly: false