apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: openhack/minecraft-server
          ports:
            - containerPort: 25565
            - containerPort: 25575
          env:
            - name: EULA
              value: "True"

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    name: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: server
    - port: 25575
      targetPort: 25575
      protocol: TCP
      name: management
  selector:
    app: minecraft-server
  type: LoadBalancer